DEFINE DYNAMIC TABLE {{ database }}.PATIENTS.PATIENT_VISIT_SUMMARY_DT(
	PATIENT_ID,
	FULL_NAME,
	CITY,
	NUMBER_OF_VISITS
) target_lag = '1 day' refresh_mode = AUTO initialize = ON_SCHEDULE warehouse = DISHA_RANI_WH
 as
SELECT
    P.PATIENT_ID,
    P.FULL_NAME,
    P.CITY,
    COUNT(DISTINCT V.VISIT_ID) AS NUMBER_OF_VISITS
FROM {{ database }}.PATIENTS.PATIENTS P
JOIN {{ database }}.PATIENTS.PATIENT_VISITS V
    ON P.PATIENT_ID = V.PATIENT_ID
GROUP BY
  P.PATIENT_ID,
    P.FULL_NAME,
    P.CITY;