name: DCM_DBT_CICD
version: 1.0.0
config-version: 2

profile: dcm_dbt_cicd

model-paths:
  - models

analysis-paths:
  - analyses

test-paths:
  - tests

seed-paths:
  - seeds

macro-paths:
  - macros

snapshot-paths:
  - snapshots

models:
  dcm_dbt_cicd:
    +materialized: view

    patients:
      +schema: PATIENTS_SILVER
      +materialized: incremental

    hospitals:
      +schema: HOSPITALS_SILVER
      +materialized: incremental
