DEFINE VIEW {{ database }}.PATIENTS.VW_PATIENTS_AGG(
	CITY,
	GENDER,
	PATIENT_COUNT,
	AVG_AGE
) as
SELECT
    CITY,
    GENDER,
    COUNT(*) AS PATIENT_COUNT,
    AVG(DATEDIFF('YEAR', DATE_OF_BIRTH, CURRENT_DATE())) AS AVG_AGE
FROM {{ database }}.PATIENTS.PATIENTS
GROUP BY
    CITY,
    GENDER;