create or replace task COPY_DEV_STAGE_TO_PROD_TASK
	warehouse=DISHA_RANI_WH
	schedule='USING CRON 00 12 * * * Asia/Kolkata'
	as COPY FILES
INTO @CICD_AUTOMATION_PROD.PATIENTS.PATIENT_VISITS_STAGE
FROM @CICD_AUTOMATION{{env_suffix}}.PATIENTS.PATIENT_VISITS_STAGE;