create or replace task INGEST_PATIENT_VISITS
	warehouse=DISHA_RANI_WH
	schedule='USING CRON 00 13 * * * Asia/Kolkata'
	as COPY INTO CICD_AUTOMATION{{env_suffix}}.PATIENTS.PATIENTS
    FROM @CICD_AUTOMATION{{env_suffix}}.PATIENTS.PATIENTS_STAGE
FILE_FORMAT = (FORMAT_NAME = 'CICD_AUTOMATION{{env_suffix}}.UTILITIES.CSV');