create or replace task INGEST_HOSPITAL_DETAILS
	warehouse=DISHA_RANI_WH
	schedule='USING CRON 00 13 * * * Asia/Kolkata'
	as COPY INTO CICD_AUTOMATION{{env_suffix}}.HOSPITALS.HOSPITAL_DETAILS
FROM @CICD_AUTOMATION{{env_suffix}}.HOSPITALS.HOSPITALS_STAGE
FILE_FORMAT = (FORMAT_NAME = 'CICD_AUTOMATION{{env_suffix}}.UTILITIES.CSV');