DEFINE TASK {{ database }}.UTILITIES.INGEST_HOSPITAL_DETAILS
	warehouse=DISHA_RANI_WH
	schedule='USING CRON 00 13 * * * Asia/Kolkata'
	as COPY INTO {{ database }}.HOSPITALS.HOSPITAL_DETAILS
FROM @{{ database }}.HOSPITALS.HOSPITALS_STAGE
FILE_FORMAT = (FORMAT_NAME = '{{ database }}.UTILITIES.CSV');